name: My first workflow

on: [push, pull_request]

jobs:
  job_1:
    name: my first job
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [10, 12, 14]

    steps:
      - uses: actions/setup-node@v2
      - name: Install Dependencies
        run: |
          npm ci 
          npm run build
        working-directory : ./temp
        shell : bash
        
        

    
  # job_2:
  #   name: my second job
  #   needs: jobs_1
  # job_3:
  #   name: my third job
  #   needs: [job_1, job_2]


    
